name: testing-ci2

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: login to ghcr    
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GHCR_TOKEN }}
          
#       - name: build and push
#         run: |
#           docker build . --tag ghcr.io/paulduchesne/docker-ghcr:latest          
          
          
          
      - name: build + push to ghcr
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
