name: testing-ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print something ${{ github.repository }} and ${{ github.actor }}
        run: echo "hallo"
        
      - name: login to ghcr    
      	uses: docker/login-action@v2
      	with:
      	    registry: ghcr.io
      	    username: ${{ github.actor }} 
      	    password: ${{ secrets.GHCR_TOKEN }}
